#!/bin/bash

cache_src () {

sudo sync
sudo sysctl -w vm.drop_caches=3 > /dev/null 2>&1

	  bot_retorno="$LINE\n"
	  bot_retorno+=" ✅🗑 Cache\Ram refreez! 🗑✅\n"
	  bot_retorno+="$LINE"

if [[ ${comando[1]} = "edit" ]]; then
	edit_msj
	menu_src
else
	comando[1]="edit"
	msj_fun
	menu_src
fi
}
