#!/bin/bash
# -*- ENCODING: UTF-8 -*-
inf(){
	if [[ ${callback_query_data[$id]} ]]; then
		bot_retorno="inf num list" && reply
	elif [[ ! -z ${comando[1]} ]]; then
		getinf "${comando[1]}"
	else
		invalido_fun
	fi

}

comand () {
	    if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then

	    	if [[ ! $(cat ${CID}|grep "${chatuser}") = "" ]]; then
	    		Botsec=$(date +%s)
	    		DateExp="$(cat ${CID}|grep -w "${chatuser}"|awk '{print $2}')"
	    		DataSec=$(date +%s --date="$DateExp")

	    		if [[ "$Botsec" -gt "$DataSec" ]]; then
	    			sed -i "/${chatuser}/ d" ${CID}
	    		fi

	    	fi

		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
		 	del_msj
			 case ${comando[0]} in
				 /[Ii]d|/[Ii]D)myid_src &;;
				 /[Mm]enu|[Mm]enu|/[Ss]tart|[Ss]tart|[Cc]omensar|/[Cc]omensar)menu_src &;;
				 /[Aa]yuda|[Aa]yuda|[Hh]elp|/[Hh]elp)ayuda_src &;;
				 /*|*)invalido_fun &;;
			 esac
		 else
		 	if [[ ${message_text[$id]} || ${callback_query_data[$id]} ]]; then
		 		del_msj
			 case ${comando[0]} in
				 /[Mm]enu|[Mm]enu|/[Ss]tart|[Ss]tart|[Cc]omensar|/[Cc]omensar)menu_src &;;
				 /[Aa]yuda|[Aa]yuda|[Hh]elp|/[Hh]elp)ayuda_src &;;
				 /[Ii]d|/[Ii]D)myid_src &;;
				 /[Ii]nstal)link_src &;;
				 /[Kk]eygen)gerar_key &;;
				 /*|*)invalido_fun &;;
			 esac
			fi
			sleep 5 
			[[ -e "/etc/donar_active.txt" ]] && donar
		 fi


	    else

	    	if [[ ${message_reply_to_message_message_id[$id]} ]]; then

	    		opc="${message_reply_to_message_text[$id]}"

	    		if [[ ! $(echo "$opc"|grep "Eliminar") = "" ]]; then
	    			opc="del"
	    		elif [[ ! $(echo "$opc"|grep "ID:") = "" ]]; then
	    			opc2=$(echo "$opc"|cut -d '\' -f1)
	    			opc2+=" Exp:${message_text[$id]}"
	    			opc="save"
	    			del_msj "${return[message_id]}"
	    		elif [[ ! $(echo "$opc"|grep "ID") = "" ]]; then
	    			del_msj "${return[message_id]}"
	    			if [[ $(cat "${CID}"|grep -w "${message_text[$id]}") = "" ]]; then
	    				bot_retorno="ID:${message_text[$id]}\n\n"
	    				bot_retorno+="Ingrese una fecha expiracion"
	    				opc="ID"
	    			else
	    				bot_retorno="$LINE\n"
	    				bot_retorno+="  ⚠️ Este ID ya existe ⚠️\n"
	    				bot_retorno+="$LINE"
	    				msj_fun
	    				sleep 2
	    				message_message_id="${return[message_id]}"
	    				del_msj
	    				return 0
	    			fi
	    		elif [[ ! $(echo "$opc"|grep "inf") = "" ]]; then
	    			del_msj "${message_reply_to_message_message_id[id]}"
	    			inf_id=$(echo $(sed -n ${message_text[$id]}p ${CID})|awk '{print $1}')
	    			getinf "$inf_id"
	    			return 0
	    		fi

				case ${opc} in
					'del')deleteID_reply;;
					'save')addID_reply "${opc2}";;
					'ID')reply;;
					*)invalido_fun;;
				esac

			elif [[ ${message_document_file_id[$id]} ]]; then
					 download_file

	    	elif [[ ${message_text[$id]} || ${callback_query_data[$id]} ]]; then
	    		del_msj
		 		case ${comando[0]} in
					 /[Mm]enu|[Mm]enu|/[Ss]tart|[Ss]tart|[Cc]omensar|/[Cc]omensar)menu_src &;;
					 /[Aa]yuda|[Aa]yuda|[Hh]elp|/[Hh]elp)ayuda_src &;;
					 /[Ii]d|/[Ii]D)myid_src &;;
					 /[Aa]dd) bot_retorno="Ingrese un ID" && reply;;
					 /[Dd]el)listID_src;;
					 /[Pp]ower)start_gen &;;
					 /[Kk]eygen)gerar_key &;;
			 		 /[Ll]ist)listID_src &;;
					 /[Rr]eboot)reboot_src &;;
			 		 /[Ii]nstal)link_src &;;
			 		 /[Cc]ache)cache_src &;;
					 /[Aa]ctualizar)update &;;
					 /[Dd]onar)donar_OnOff &;;
					 /[Ee]xtra)extra &;;
					 /[Ii]nfo)inf &;;
			 		 /*|*)invalido_fun &;;
				esac

			fi

	    fi
}
