#!/bin/bash
# -*- ENCODING: UTF-8 -*-

listID_src(){
	VPSsec=$(date +%s)

	#if [[ ${message_text[$id]} = "/del" ]]; then
	if [[ ${comando[0]} = "/del" ]]; then
		bot_retorno="_______Eliminar un Usuario_______\n"
	else
		bot_retorno="________Lista de usuarios________\n"
	fi
	#bot_retorno+="$LINE\n"
	bot_retorno+="$(printf "%-12s %-24s" N° ID DIAS)\n"
	bot_retorno+="$LINE\n"

	n=1
	while IFS= read -r line
	do
		line1=$(echo ${line}|awk '{print $1}')
		line2=$(echo ${line}|awk '{print $2}')

		DataSec=$(date +%s --date="$line2")

		if [[ "$VPSsec" -gt "$DataSec" ]]; then
			EXPTIME="[Exp]"
		else
			EXPTIME="[$(($(($DataSec - $VPSsec)) / 86400))]"
		fi

		line3=${#line1}
		line4=$((15 - $line3))
		unset esp
		for (( i = 0; i < ${line4}; i++ )); do
				esp+="  "
		done
		line5="$line1+$esp"

		if [[ (( $n -le 9 )) ]]; then
			bot_retorno+="  [$n] - ${line5}${EXPTIME}\n"
		else
			bot_retorno+="[$n] - ${line5}${EXPTIME}\n"
		fi

		let n++
	done <<< $(cat ${CID})
	
	bot_retorno+="$LINE\n"

	#if [[ ${message_text[$id]} = "/del" ]]; then
	if [[ ${comando[0]} = "/del" ]]; then
		reply
	#elif [[ ${message_text[$id]} = "/list" ]]; then
	elif [[ ${comando[0]} = "/list" ]]; then
		msj_fun
	fi
}

# datexp=$(date "+%F" -d " + $3 days")
# VPSsec=$(date +%s)
# DateExp="$(cat ${USRdatabase}|grep -w "${user}"|cut -d'|' -f3)"
# DataSec=$(date +%s --date="$DateExp")
# if [[ "$VPSsec" -gt "$DataSec" ]]; then
  #EXPTIME="${red}[Exp]"
#else
  #EXPTIME="${gren}[$(($(($DataSec - $VPSsec)) / 86400))]"
#fi
