#!/bin/bash

menu_src () {
	 if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
		   	 bot_retorno="━━━━━COMANDOS━━━━━\n"
			 bot_retorno+="/ID (muestra sus ID)\n"
			 bot_retorno+="/menu (muestra este menu)\n"
			 bot_retorno+="/ayuda (ayuda de los comandos)\n"
			 bot_retorno+="$LINE\n"
			 comand_boton "user"
		 else
		 	 bot_retorno="━━━━━COMANDOS━━━━━\n"
			 bot_retorno+="/ID (muestra sus ID)\n"
			 bot_retorno+="/instal (link de instalacion)\n"
			 bot_retorno+="/menu (muestra este menu)\n"
			 bot_retorno+="/ayuda (ayuda de los comandos)\n"
			 bot_retorno+="$LINE"
			 comand_boton "user2"
		 fi
		 
	 else

	 	#HORA Y FECHA
	 	unset _hora
	 	unset _fecha
	 	_hora=$(printf '%(%H:%M:%S)T') 
	 	_fecha=$(printf '%(%D)T') 

	 	#PROCESSADOR
	 	unset _core
	 	unset _usop
	 	_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
	 	_usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")

	 	#MEMORIA RAM
	 	unset ram1
	 	unset ram2
	 	unset ram3
	 	ram1=$(free -h | grep -i mem | awk {'print $2'})
	 	ram2=$(free -h | grep -i mem | awk {'print $4'})
	 	ram3=$(free -h | grep -i mem | awk {'print $3'})
	 	
	 	unset _ram
	 	unset _sor
	 	_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
	 	_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")

	 	unset os_sys
	 	os_sys=$(echo $(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/      //')) && echo $system|awk '{print $1, $2}'

		 unset PID_GEN
		 PID_GEN=$(ps x|grep -v grep|grep "BotGen-server.sh")
		 [[ ! $PID_GEN ]] && PID_GEN='(Offline) ❌' || PID_GEN='(Online) ✅'

		 unset usadas
		 usadas="$(cat /etc/http-instas)"
		 [[ ! $usadas ]] && k_used="0" || k_used="$usadas"

		 bot_retorno="$LINE\n"
		 bot_retorno+="Gen $PID_GEN | Keys Used [$k_used]\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="<u>S.O</u>: $os_sys\n"
		 bot_retorno+="<u>Su IP es</u>: $(meu_ip)\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="<u>Ram</u>: $ram1 || <u>En Uso</u>: $_usor\n"
		 bot_retorno+="<u>Usada</u>: $ram3 || <u>Libre</u>: $ram2\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="<u>CPU</u>: $_core || <u>En Uso</u>: $_usop\n"
		 bot_retorno+="$LINE\n"
		 bot_retorno+="<u>Fecha</u>: $_fecha  <u>Hora</u>: $_hora\n"
		 bot_retorno+="$LINE\n"

		 comand_boton "conf"
	 fi	
}