#!/bin/bash

start_gen2 () {
unset PIDGEN
PIDGEN=$(ps aux|grep -v grep|grep "BotGen-server.sh")

if [[ ! $PIDGEN ]]; then
	systemctl start BotGen-server 
local bot_retorno="$LINE\n"
          bot_retorno+="Generador: <u>Online</u> ✅\n"
	  bot_retorno+="$LINE\n"
msj_fun
else
	systemctl stop BotGen-server
local bot_retorno="$LINE\n"
          bot_retorno+="Generador: <u>Offline</u> ❌\n"
	  bot_retorno+="$LINE\n"
msj_fun
fi
}

start_gen () {
unset PIDGEN
PIDGEN=$(ps aux|grep -v grep|grep "BotGen-server.sh")

if [[ ! $PIDGEN ]]; then
	systemctl start BotGen-server
	menu_src
else
	systemctl stop BotGen-server
	menu_src
fi
}
