#!/bin/bash

start_gen () {
unset PIDGEN
PIDGEN=$(ps aux|grep -v grep|grep "BotGen-server.sh")

if [[ ! $PIDGEN ]]; then
	systemctl start BotGen-server
	menu_src
else
	systemctl stop BotGen-server
	menu_src
fi
}
